import { transform } from './unicode/transform';
import { generateCombinationStyles } from './combination-styles';
import type { CharMap, DecoratorFn } from './unicode/transform';
import {
  strikethrough,
  underline,
  doubleUnderline,
  zalgoLight,
  zalgoMedium,
  zalgoHeavy,
  vaporwaveSpace,
  hearts,
  stars,
  sparkles,
  flowers,
  crown,
} from './unicode/decorators';
import { BOLD_MAP } from './unicode/maps/bold';
import { ITALIC_MAP } from './unicode/maps/italic';
import { BOLD_ITALIC_MAP } from './unicode/maps/bold-italic';
import { CURSIVE_MAP } from './unicode/maps/cursive';
import { BOLD_CURSIVE_MAP } from './unicode/maps/bold-cursive';
import { GOTHIC_MAP } from './unicode/maps/gothic';
import { BOLD_GOTHIC_MAP } from './unicode/maps/bold-gothic';
import { DOUBLE_STRUCK_MAP } from './unicode/maps/double-struck';
import { MONOSPACE_MAP } from './unicode/maps/monospace';
import { SANS_SERIF_MAP } from './unicode/maps/sans-serif';
import { SANS_BOLD_MAP } from './unicode/maps/sans-bold';
import { SANS_ITALIC_MAP } from './unicode/maps/sans-italic';
import { SANS_BOLD_ITALIC_MAP } from './unicode/maps/sans-bold-italic';
import { CIRCLED_MAP } from './unicode/maps/circled';
import { NEGATIVE_CIRCLED_MAP } from './unicode/maps/negative-circled';
import { SQUARED_MAP } from './unicode/maps/squared';
import { NEGATIVE_SQUARED_MAP } from './unicode/maps/negative-squared';
import { PARENTHESIZED_MAP } from './unicode/maps/parenthesized';
import { FULLWIDTH_MAP } from './unicode/maps/fullwidth';
import { SMALL_CAPS_MAP } from './unicode/maps/small-caps';
import { SUPERSCRIPT_MAP } from './unicode/maps/superscript';
import { SUBSCRIPT_MAP } from './unicode/maps/subscript';
import { UPSIDE_DOWN_MAP } from './unicode/maps/upside-down';
import { MIRRORED_MAP } from './unicode/maps/mirrored';

export type StyleCategory =
  | 'script'
  | 'decorative'
  | 'geometric'
  | 'effect'
  | 'width'
  | 'transform'
  | 'weight';

export type PlatformId =
  | 'instagram'
  | 'tiktok'
  | 'discord'
  | 'twitter'
  | 'facebook'
  | 'whatsapp'
  | 'youtube';

export interface StyleDefinition {
  id: string;
  name: string;
  description: string;
  category: StyleCategory;
  tags: string[];
  map: CharMap;
  decorator?: DecoratorFn;
  decoratorName?: string;
  example: string;
  platforms: PlatformId[];
  relatedStyles: string[];
  seoKeywords: string[];
  searchVolume: number;
}

// Helper for upside-down which needs reversal
const upsideDownDecorator: DecoratorFn = (text: string) => text.split('').reverse().join('');

// Helper for mirrored which needs reversal
const mirroredDecorator: DecoratorFn = (text: string) => text.split('').reverse().join('');

// Pass-through map for decorator-only styles
const PASS_MAP: CharMap = {};

export const STYLES: StyleDefinition[] = [
  // ── Tier 1 ──────────────────────────────────────────────────────────────────
  {
    id: 'cursive-font',
    name: 'Cursive Font',
    description: 'Elegant math script letters that look like flowing cursive handwriting.',
    category: 'script',
    tags: ['cursive', 'script', 'elegant', 'fancy', 'handwriting'],
    map: CURSIVE_MAP,
    example: transform('Hello World', CURSIVE_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp', 'discord'],
    relatedStyles: ['bold-cursive-font', 'italic-font', 'bold-italic-font', 'gothic-font', 'small-caps'],
    seoKeywords: ['cursive font generator', 'cursive text generator', 'fancy cursive letters', 'cursive writing generator'],
    searchVolume: 135000,
  },
  {
    id: 'bold-text',
    name: 'Bold Text',
    description: 'Mathematical bold Unicode letters that appear bold on any platform.',
    category: 'weight',
    tags: ['bold', 'strong', 'emphasis', 'thick'],
    map: BOLD_MAP,
    example: transform('Hello World', BOLD_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp', 'discord', 'youtube'],
    relatedStyles: ['bold-italic-font', 'sans-bold', 'bold-cursive-font', 'bold-gothic-font', 'italic-font'],
    seoKeywords: ['bold text generator', 'bold font generator', 'bold letters copy paste', 'bold unicode text'],
    searchVolume: 110000,
  },
  {
    id: 'italic-font',
    name: 'Italic Font',
    description: 'Slanted math italic letters for stylish emphasis in bios and captions.',
    category: 'script',
    tags: ['italic', 'slanted', 'emphasis', 'math'],
    map: ITALIC_MAP,
    example: transform('Hello World', ITALIC_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['bold-italic-font', 'sans-italic', 'cursive-font', 'bold-text', 'sans-bold-italic'],
    seoKeywords: ['italic font generator', 'italic text generator', 'italic letters copy paste', 'slanted text'],
    searchVolume: 90000,
  },
  {
    id: 'bold-italic-font',
    name: 'Bold Italic Font',
    description: 'Combined bold and italic math letters — powerful and expressive.',
    category: 'weight',
    tags: ['bold', 'italic', 'emphasis', 'combined'],
    map: BOLD_ITALIC_MAP,
    example: transform('Hello World', BOLD_ITALIC_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['bold-text', 'italic-font', 'sans-bold-italic', 'cursive-font', 'bold-cursive-font'],
    seoKeywords: ['bold italic font generator', 'bold italic text', 'bold italic letters', 'fancy bold italic'],
    searchVolume: 74000,
  },
  {
    id: 'gothic-font',
    name: 'Gothic Font',
    description: 'Medieval Fraktur blackletter style — dramatic and dark.',
    category: 'script',
    tags: ['gothic', 'fraktur', 'blackletter', 'medieval', 'dark'],
    map: GOTHIC_MAP,
    example: transform('Hello World', GOTHIC_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['bold-gothic-font', 'bold-cursive-font', 'cursive-font', 'double-struck', 'bold-text'],
    seoKeywords: ['gothic font generator', 'gothic text generator', 'blackletter font', 'fraktur text generator'],
    searchVolume: 68000,
  },
  {
    id: 'strikethrough-text',
    name: 'Strikethrough Text',
    description: 'Text with a line through the middle using Unicode combining characters.',
    category: 'effect',
    tags: ['strikethrough', 'crossed', 'deleted', 'effect'],
    map: PASS_MAP,
    decorator: strikethrough,
    example: transform('Hello World', PASS_MAP, strikethrough),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord', 'whatsapp'],
    relatedStyles: ['underline-text', 'double-underline-text', 'zalgo-light', 'wavy-text', 'bold-text'],
    seoKeywords: ['strikethrough text generator', 'strikethrough font', 'crossed out text', 'strikethrough letters'],
    searchVolume: 60000,
  },
  {
    id: 'small-caps',
    name: 'Small Caps',
    description: 'All-caps text using smaller capital letterforms — clean and distinctive.',
    category: 'transform',
    tags: ['small caps', 'capitals', 'uppercase', 'professional'],
    map: SMALL_CAPS_MAP,
    example: transform('Hello World', SMALL_CAPS_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp', 'discord'],
    relatedStyles: ['cursive-font', 'superscript-text', 'fullwidth-text', 'monospace-font', 'bold-text'],
    seoKeywords: ['small caps generator', 'small capital letters', 'small caps text', 'tiny capital letters'],
    searchVolume: 55000,
  },
  {
    id: 'double-struck',
    name: 'Double-Struck',
    description: 'Blackboard bold letters used in mathematics — unique and eye-catching.',
    category: 'decorative',
    tags: ['double struck', 'blackboard bold', 'math', 'outline'],
    map: DOUBLE_STRUCK_MAP,
    example: transform('Hello World', DOUBLE_STRUCK_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['gothic-font', 'bold-gothic-font', 'circled-text', 'monospace-font', 'bold-text'],
    seoKeywords: ['double struck text', 'blackboard bold generator', 'double struck letters', 'math font generator'],
    searchVolume: 48000,
  },
  {
    id: 'upside-down-text',
    name: 'Upside Down Text',
    description: 'Flip your text upside down using mirrored Unicode equivalents.',
    category: 'transform',
    tags: ['upside down', 'flipped', 'inverted', 'reversed'],
    map: UPSIDE_DOWN_MAP,
    decorator: upsideDownDecorator,
    example: transform('Hello World', UPSIDE_DOWN_MAP, upsideDownDecorator),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp', 'discord'],
    relatedStyles: ['mirrored-text', 'zalgo-light', 'strikethrough-text', 'fullwidth-text', 'vaporwave-text'],
    seoKeywords: ['upside down text generator', 'flip text upside down', 'inverted text', 'flipped letters'],
    searchVolume: 45000,
  },
  {
    id: 'vaporwave-text',
    name: 'Vaporwave Text',
    description: 'Fullwidth spaced characters — the iconic aesthetic of 80s retro futurism.',
    category: 'width',
    tags: ['vaporwave', 'aesthetic', 'fullwidth', 'spaced', 'retro'],
    map: FULLWIDTH_MAP,
    decorator: vaporwaveSpace,
    example: transform('Hello World', FULLWIDTH_MAP, vaporwaveSpace),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['fullwidth-text', 'upside-down-text', 'zalgo-light', 'aesthetic-text', 'mirrored-text'],
    seoKeywords: ['vaporwave text generator', 'aesthetic text generator', 'vaporwave font', 'wide text generator'],
    searchVolume: 42000,
  },

  // ── Tier 2 ──────────────────────────────────────────────────────────────────
  {
    id: 'bold-cursive-font',
    name: 'Bold Cursive Font',
    description: 'Bold script letters — thick, flowing, and impossible to ignore.',
    category: 'script',
    tags: ['bold', 'cursive', 'script', 'thick', 'handwriting'],
    map: BOLD_CURSIVE_MAP,
    example: transform('Hello World', BOLD_CURSIVE_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp'],
    relatedStyles: ['cursive-font', 'bold-italic-font', 'bold-text', 'gothic-font', 'italic-font'],
    seoKeywords: ['bold cursive font', 'bold script generator', 'thick cursive letters', 'bold handwriting font'],
    searchVolume: 38000,
  },
  {
    id: 'monospace-font',
    name: 'Monospace Font',
    description: 'Fixed-width typewriter-style characters — perfect for code and tech aesthetics.',
    category: 'decorative',
    tags: ['monospace', 'typewriter', 'code', 'fixed-width', 'terminal'],
    map: MONOSPACE_MAP,
    example: transform('Hello World', MONOSPACE_MAP),
    platforms: ['discord', 'twitter', 'instagram', 'facebook', 'tiktok'],
    relatedStyles: ['fullwidth-text', 'bold-text', 'sans-serif-font', 'double-struck', 'small-caps'],
    seoKeywords: ['monospace font generator', 'typewriter text generator', 'monospace text', 'code font generator'],
    searchVolume: 35000,
  },
  {
    id: 'circled-text',
    name: 'Circled Text',
    description: 'Each letter wrapped in a circle — playful and attention-grabbing.',
    category: 'geometric',
    tags: ['circled', 'enclosed', 'bubble', 'geometric', 'cute'],
    map: CIRCLED_MAP,
    example: transform('Hello World', CIRCLED_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord', 'whatsapp'],
    relatedStyles: ['negative-circled', 'squared-text', 'negative-squared', 'parenthesized-text', 'bold-text'],
    seoKeywords: ['circled text generator', 'circle letters generator', 'bubble letters', 'circled alphabet'],
    searchVolume: 32000,
  },
  {
    id: 'bold-gothic-font',
    name: 'Bold Gothic Font',
    description: 'Heavy blackletter Fraktur — the most dramatic medieval font style.',
    category: 'script',
    tags: ['bold', 'gothic', 'fraktur', 'heavy', 'blackletter'],
    map: BOLD_GOTHIC_MAP,
    example: transform('Hello World', BOLD_GOTHIC_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['gothic-font', 'bold-text', 'double-struck', 'bold-cursive-font', 'sans-bold'],
    seoKeywords: ['bold gothic font', 'bold fraktur generator', 'heavy blackletter', 'bold medieval font'],
    searchVolume: 28000,
  },
  {
    id: 'fullwidth-text',
    name: 'Fullwidth Text',
    description: 'Wide double-width characters from the Unicode fullwidth block.',
    category: 'width',
    tags: ['fullwidth', 'wide', 'double-width', 'aesthetic', 'japanese'],
    map: FULLWIDTH_MAP,
    example: transform('Hello World', FULLWIDTH_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['vaporwave-text', 'upside-down-text', 'small-caps', 'monospace-font', 'superscript-text'],
    seoKeywords: ['fullwidth text generator', 'wide text generator', 'full width letters', 'aesthetic text'],
    searchVolume: 26000,
  },
  {
    id: 'underline-text',
    name: 'Underline Text',
    description: 'Underlined text using Unicode combining underline diacritics.',
    category: 'effect',
    tags: ['underline', 'underlined', 'emphasis', 'effect'],
    map: PASS_MAP,
    decorator: underline,
    example: transform('Hello World', PASS_MAP, underline),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp', 'discord'],
    relatedStyles: ['strikethrough-text', 'double-underline-text', 'wavy-text', 'bold-text', 'italic-font'],
    seoKeywords: ['underline text generator', 'underlined text copy paste', 'underline font', 'underline letters'],
    searchVolume: 25000,
  },
  {
    id: 'sans-serif-font',
    name: 'Sans-Serif Font',
    description: 'Clean mathematical sans-serif letters — modern and highly readable.',
    category: 'decorative',
    tags: ['sans-serif', 'clean', 'modern', 'minimal'],
    map: SANS_SERIF_MAP,
    example: transform('Hello World', SANS_SERIF_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['sans-bold', 'sans-italic', 'sans-bold-italic', 'bold-text', 'monospace-font'],
    seoKeywords: ['sans serif font generator', 'clean font generator', 'modern text generator', 'sans text'],
    searchVolume: 24000,
  },
  {
    id: 'zalgo-text',
    name: 'Zalgo Text',
    description: 'Corrupted glitchy text with stacking diacritics — creepy and surreal.',
    category: 'effect',
    tags: ['zalgo', 'glitch', 'creepy', 'corrupted', 'horror'],
    map: PASS_MAP,
    decorator: zalgoMedium,
    example: transform('Hello', PASS_MAP, zalgoMedium),
    platforms: ['discord', 'twitter', 'instagram', 'facebook'],
    relatedStyles: ['zalgo-heavy', 'zalgo-light', 'strikethrough-text', 'upside-down-text', 'wavy-text'],
    seoKeywords: ['zalgo text generator', 'glitch text generator', 'creepy text generator', 'corrupted text'],
    searchVolume: 22000,
  },
  {
    id: 'superscript-text',
    name: 'Superscript Text',
    description: 'Raised mini characters — makes your text look like footnotes or math.',
    category: 'transform',
    tags: ['superscript', 'raised', 'tiny', 'small', 'exponent'],
    map: SUPERSCRIPT_MAP,
    example: transform('Hello World', SUPERSCRIPT_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'discord', 'whatsapp'],
    relatedStyles: ['subscript-text', 'small-caps', 'fullwidth-text', 'monospace-font', 'bold-text'],
    seoKeywords: ['superscript text generator', 'superscript letters', 'raised text generator', 'exponent text'],
    searchVolume: 20000,
  },
  {
    id: 'negative-circled',
    name: 'Negative Circled',
    description: 'Inverted filled circle letters — bold black circles with white letters inside.',
    category: 'geometric',
    tags: ['negative', 'circled', 'filled', 'black', 'bold'],
    map: NEGATIVE_CIRCLED_MAP,
    example: transform('Hello World', NEGATIVE_CIRCLED_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['circled-text', 'negative-squared', 'squared-text', 'parenthesized-text', 'bold-text'],
    seoKeywords: ['negative circled letters', 'black circle letters', 'filled circle text', 'dark circle alphabet'],
    searchVolume: 18000,
  },

  // ── Tier 3 ──────────────────────────────────────────────────────────────────
  {
    id: 'sans-bold',
    name: 'Sans-Serif Bold',
    description: 'Bold sans-serif mathematics letters — thick and geometric.',
    category: 'weight',
    tags: ['sans', 'bold', 'geometric', 'thick', 'clean'],
    map: SANS_BOLD_MAP,
    example: transform('Hello World', SANS_BOLD_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['bold-text', 'sans-serif-font', 'sans-bold-italic', 'sans-italic', 'bold-italic-font'],
    seoKeywords: ['sans bold font generator', 'bold sans serif text', 'geometric bold letters', 'thick sans font'],
    searchVolume: 16000,
  },
  {
    id: 'sans-italic',
    name: 'Sans-Serif Italic',
    description: 'Slanted sans-serif letters — contemporary and sophisticated.',
    category: 'decorative',
    tags: ['sans', 'italic', 'slanted', 'modern'],
    map: SANS_ITALIC_MAP,
    example: transform('Hello World', SANS_ITALIC_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['italic-font', 'sans-serif-font', 'sans-bold-italic', 'sans-bold', 'bold-italic-font'],
    seoKeywords: ['sans italic font generator', 'slanted sans text', 'modern italic font', 'sans serif italic'],
    searchVolume: 15000,
  },
  {
    id: 'sans-bold-italic',
    name: 'Sans-Serif Bold Italic',
    description: 'The boldest, most dynamic style — thick slanted sans letters.',
    category: 'weight',
    tags: ['sans', 'bold', 'italic', 'dynamic', 'powerful'],
    map: SANS_BOLD_ITALIC_MAP,
    example: transform('Hello World', SANS_BOLD_ITALIC_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['bold-italic-font', 'sans-bold', 'sans-italic', 'bold-text', 'sans-serif-font'],
    seoKeywords: ['sans bold italic generator', 'bold italic sans serif', 'thick slanted text', 'dynamic font'],
    searchVolume: 14000,
  },
  {
    id: 'squared-text',
    name: 'Squared Text',
    description: 'Each letter inside a square box — structured and eye-catching.',
    category: 'geometric',
    tags: ['squared', 'boxed', 'geometric', 'structured'],
    map: SQUARED_MAP,
    example: transform('Hello World', SQUARED_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['negative-squared', 'circled-text', 'negative-circled', 'parenthesized-text', 'bold-text'],
    seoKeywords: ['squared text generator', 'box letters generator', 'squared alphabet', 'boxed letters'],
    searchVolume: 13000,
  },
  {
    id: 'negative-squared',
    name: 'Negative Squared',
    description: 'Black filled square letters — bold and assertive block-style text.',
    category: 'geometric',
    tags: ['negative', 'squared', 'black', 'filled', 'bold'],
    map: NEGATIVE_SQUARED_MAP,
    example: transform('Hello World', NEGATIVE_SQUARED_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['squared-text', 'negative-circled', 'circled-text', 'bold-text', 'parenthesized-text'],
    seoKeywords: ['negative squared letters', 'black square letters', 'filled square text', 'dark square alphabet'],
    searchVolume: 12000,
  },
  {
    id: 'parenthesized-text',
    name: 'Parenthesized Text',
    description: 'Letters in parentheses — a quirky and charming style.',
    category: 'geometric',
    tags: ['parenthesized', 'brackets', 'enclosed', 'quirky'],
    map: PARENTHESIZED_MAP,
    example: transform('Hello World', PARENTHESIZED_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['circled-text', 'squared-text', 'negative-circled', 'negative-squared', 'bold-text'],
    seoKeywords: ['parenthesized text generator', 'letters in parentheses', 'bracket text generator', 'enclosed letters'],
    searchVolume: 11000,
  },
  {
    id: 'double-underline-text',
    name: 'Double Underline',
    description: 'Text with two parallel underlines — strong emphasis and classic formatting.',
    category: 'effect',
    tags: ['double underline', 'emphasis', 'underline', 'strong'],
    map: PASS_MAP,
    decorator: doubleUnderline,
    example: transform('Hello World', PASS_MAP, doubleUnderline),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['underline-text', 'strikethrough-text', 'wavy-text', 'bold-text', 'italic-font'],
    seoKeywords: ['double underline text', 'double underline generator', 'two underline text', 'double line text'],
    searchVolume: 10000,
  },
  {
    id: 'subscript-text',
    name: 'Subscript Text',
    description: 'Lowered small characters — useful for chemistry formulas and stylistic effects.',
    category: 'transform',
    tags: ['subscript', 'lowered', 'small', 'chemistry'],
    map: SUBSCRIPT_MAP,
    example: transform('Hello World', SUBSCRIPT_MAP),
    platforms: ['instagram', 'discord', 'twitter', 'facebook', 'tiktok'],
    relatedStyles: ['superscript-text', 'small-caps', 'monospace-font', 'fullwidth-text', 'bold-text'],
    seoKeywords: ['subscript text generator', 'subscript letters', 'lowered text generator', 'small text below'],
    searchVolume: 9500,
  },
  {
    id: 'mirrored-text',
    name: 'Mirrored Text',
    description: 'Horizontally flipped characters — your text as seen in a mirror.',
    category: 'transform',
    tags: ['mirrored', 'flipped', 'reversed', 'horizontal'],
    map: MIRRORED_MAP,
    decorator: mirroredDecorator,
    example: transform('Hello World', MIRRORED_MAP, mirroredDecorator),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['upside-down-text', 'vaporwave-text', 'zalgo-light', 'fullwidth-text', 'strikethrough-text'],
    seoKeywords: ['mirrored text generator', 'mirror text generator', 'reversed text', 'flip text horizontally'],
    searchVolume: 9000,
  },
  {
    id: 'zalgo-light',
    name: 'Zalgo Light',
    description: 'Subtle glitchy text with light stacking diacritics — eerie but readable.',
    category: 'effect',
    tags: ['zalgo', 'glitch', 'light', 'subtle', 'eerie'],
    map: PASS_MAP,
    decorator: zalgoLight,
    example: transform('Hello World', PASS_MAP, zalgoLight),
    platforms: ['discord', 'twitter', 'instagram', 'facebook'],
    relatedStyles: ['zalgo-text', 'zalgo-heavy', 'strikethrough-text', 'wavy-text', 'upside-down-text'],
    seoKeywords: ['zalgo light text', 'light glitch text', 'subtle zalgo', 'light corrupted text'],
    searchVolume: 8500,
  },
  {
    id: 'zalgo-heavy',
    name: 'Zalgo Heavy',
    description: 'Extreme zalgo text — completely overwhelmed with diacritics for maximum chaos.',
    category: 'effect',
    tags: ['zalgo', 'heavy', 'extreme', 'chaos', 'horror'],
    map: PASS_MAP,
    decorator: zalgoHeavy,
    example: transform('Hello', PASS_MAP, zalgoHeavy),
    platforms: ['discord', 'twitter'],
    relatedStyles: ['zalgo-text', 'zalgo-light', 'strikethrough-text', 'upside-down-text', 'mirrored-text'],
    seoKeywords: ['zalgo heavy text', 'extreme zalgo generator', 'heavy glitch text', 'maximum zalgo'],
    searchVolume: 7500,
  },

  // ── Tier 4 ──────────────────────────────────────────────────────────────────
  {
    id: 'hearts-text',
    name: 'Hearts Text',
    description: 'Wraps your text in heart symbols — perfect for romantic and cute posts.',
    category: 'decorative',
    tags: ['hearts', 'love', 'romantic', 'cute', 'symbols'],
    map: PASS_MAP,
    decorator: hearts,
    example: transform('Hello World', PASS_MAP, hearts),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp'],
    relatedStyles: ['stars-text', 'sparkles-text', 'flowers-text', 'crown-text', 'cursive-font'],
    seoKeywords: ['heart text generator', 'heart font', 'love text generator', 'heart symbols text'],
    searchVolume: 7000,
  },
  {
    id: 'stars-text',
    name: 'Stars Text',
    description: 'Surrounds your text with star symbols — glam and attention-grabbing.',
    category: 'decorative',
    tags: ['stars', 'sparkle', 'glam', 'symbols', 'shine'],
    map: PASS_MAP,
    decorator: stars,
    example: transform('Hello World', PASS_MAP, stars),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp'],
    relatedStyles: ['hearts-text', 'sparkles-text', 'crown-text', 'flowers-text', 'cursive-font'],
    seoKeywords: ['star text generator', 'star font generator', 'stars text copy paste', 'star symbols text'],
    searchVolume: 6500,
  },
  {
    id: 'sparkles-text',
    name: 'Sparkles Text',
    description: 'Frames your text with sparkle emoji — brilliant and magical.',
    category: 'decorative',
    tags: ['sparkles', 'magical', 'glitter', 'shine', 'emoji'],
    map: PASS_MAP,
    decorator: sparkles,
    example: transform('Hello World', PASS_MAP, sparkles),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp'],
    relatedStyles: ['stars-text', 'hearts-text', 'flowers-text', 'crown-text', 'cursive-font'],
    seoKeywords: ['sparkle text generator', 'sparkles font', 'glitter text generator', 'magic text generator'],
    searchVolume: 6200,
  },
  {
    id: 'flowers-text',
    name: 'Flowers Text',
    description: 'Floral symbols around your text — elegant, feminine, and charming.',
    category: 'decorative',
    tags: ['flowers', 'floral', 'nature', 'elegant', 'feminine'],
    map: PASS_MAP,
    decorator: flowers,
    example: transform('Hello World', PASS_MAP, flowers),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp'],
    relatedStyles: ['hearts-text', 'stars-text', 'crown-text', 'sparkles-text', 'cursive-font'],
    seoKeywords: ['flower text generator', 'floral font generator', 'flower symbols text', 'flower letters'],
    searchVolume: 5800,
  },
  {
    id: 'crown-text',
    name: 'Crown Text',
    description: 'Royal crown symbols flanking your text — regal and commanding.',
    category: 'decorative',
    tags: ['crown', 'royal', 'regal', 'king', 'queen'],
    map: PASS_MAP,
    decorator: crown,
    example: transform('Hello World', PASS_MAP, crown),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook'],
    relatedStyles: ['stars-text', 'hearts-text', 'sparkles-text', 'flowers-text', 'bold-text'],
    seoKeywords: ['crown text generator', 'royal font generator', 'king queen text', 'crown letters'],
    searchVolume: 5500,
  },
  {
    id: 'wavy-text',
    name: 'Wavy Text',
    description: 'Text with a wavy tilde combining diacritic — flowing and musical.',
    category: 'effect',
    tags: ['wavy', 'tilde', 'wave', 'flowing', 'music'],
    map: PASS_MAP,
    decorator: (text: string) => [...text].map(c => c === ' ' ? c : c + '̃').join(''),
    example: transform('Hello World', PASS_MAP, (t) => [...t].map(c => c === ' ' ? c : c + '̃').join('')),
    platforms: ['instagram', 'tiktok', 'twitter', 'discord'],
    relatedStyles: ['strikethrough-text', 'underline-text', 'zalgo-light', 'bold-text', 'italic-font'],
    seoKeywords: ['wavy text generator', 'wave text generator', 'wavy letters', 'tilde text'],
    searchVolume: 5200,
  },
  {
    id: 'aesthetic-text',
    name: 'Aesthetic Text',
    description: 'Fullwidth spaced text without vaporwave decoration — pure soft aesthetic.',
    category: 'width',
    tags: ['aesthetic', 'soft', 'pastel', 'spaced', 'tumblr'],
    map: FULLWIDTH_MAP,
    decorator: (text: string) => [...text].join(' '),
    example: transform('Hello World', FULLWIDTH_MAP, (t) => [...t].join(' ')),
    platforms: ['instagram', 'tiktok', 'twitter', 'tumblr' as PlatformId],
    relatedStyles: ['vaporwave-text', 'fullwidth-text', 'small-caps', 'cursive-font', 'italic-font'],
    seoKeywords: ['aesthetic text generator', 'aesthetic font generator', 'soft aesthetic text', 'aesthetic letters'],
    searchVolume: 5000,
  },
  {
    id: 'bold-sans-italic',
    name: 'Bold Sans Italic',
    description: 'Alias for sans-serif bold italic — same powerful slanted thick letters.',
    category: 'weight',
    tags: ['bold', 'sans', 'italic', 'powerful'],
    map: SANS_BOLD_ITALIC_MAP,
    example: transform('Hello World', SANS_BOLD_ITALIC_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['sans-bold-italic', 'bold-italic-font', 'sans-bold', 'bold-text', 'italic-font'],
    seoKeywords: ['bold sans italic font', 'bold slanted text', 'heavy italic sans', 'thick italic letters'],
    searchVolume: 4800,
  },
  {
    id: 'bold-underline-text',
    name: 'Bold Underline',
    description: 'Bold mathematical letters with a combining underline — strong and clear.',
    category: 'effect',
    tags: ['bold', 'underline', 'emphasis', 'strong', 'combined'],
    map: BOLD_MAP,
    decorator: underline,
    example: transform('Hello World', BOLD_MAP, underline),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['bold-text', 'underline-text', 'strikethrough-text', 'double-underline-text', 'bold-italic-font'],
    seoKeywords: ['bold underline text', 'bold underlined letters', 'thick underline text', 'bold underline generator'],
    searchVolume: 4500,
  },
  {
    id: 'italic-strikethrough',
    name: 'Italic Strikethrough',
    description: 'Slanted italic letters crossed out — expressive and editorial.',
    category: 'effect',
    tags: ['italic', 'strikethrough', 'combined', 'editorial'],
    map: ITALIC_MAP,
    decorator: strikethrough,
    example: transform('Hello World', ITALIC_MAP, strikethrough),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['italic-font', 'strikethrough-text', 'bold-strikethrough', 'underline-text', 'bold-italic-font'],
    seoKeywords: ['italic strikethrough text', 'slanted crossed out text', 'italic crossed text', 'strike italic'],
    searchVolume: 4200,
  },
  {
    id: 'bold-strikethrough',
    name: 'Bold Strikethrough',
    description: 'Bold letters with a combining strikethrough line — assertive and striking.',
    category: 'effect',
    tags: ['bold', 'strikethrough', 'combined', 'assertive'],
    map: BOLD_MAP,
    decorator: strikethrough,
    example: transform('Hello World', BOLD_MAP, strikethrough),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['bold-text', 'strikethrough-text', 'italic-strikethrough', 'underline-text', 'bold-underline-text'],
    seoKeywords: ['bold strikethrough text', 'bold crossed out text', 'thick strikethrough', 'bold strike font'],
    searchVolume: 4000,
  },
  {
    id: 'cursive-underline',
    name: 'Cursive Underline',
    description: 'Elegant script letters with a combining underline — graceful and refined.',
    category: 'script',
    tags: ['cursive', 'underline', 'elegant', 'refined', 'combined'],
    map: CURSIVE_MAP,
    decorator: underline,
    example: transform('Hello World', CURSIVE_MAP, underline),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook'],
    relatedStyles: ['cursive-font', 'bold-cursive-font', 'underline-text', 'italic-font', 'bold-underline-text'],
    seoKeywords: ['cursive underline text', 'script underline font', 'underlined cursive', 'fancy underline'],
    searchVolume: 3800,
  },
  {
    id: 'gothic-bold-underline',
    name: 'Gothic Underline',
    description: 'Gothic Fraktur letters with a combining underline — medieval meets modern.',
    category: 'script',
    tags: ['gothic', 'underline', 'medieval', 'combined'],
    map: GOTHIC_MAP,
    decorator: underline,
    example: transform('Hello World', GOTHIC_MAP, underline),
    platforms: ['instagram', 'tiktok', 'twitter', 'discord'],
    relatedStyles: ['gothic-font', 'bold-gothic-font', 'underline-text', 'strikethrough-text', 'cursive-underline'],
    seoKeywords: ['gothic underline text', 'fraktur underline', 'gothic underlined font', 'dark underline text'],
    searchVolume: 3500,
  },
  {
    id: 'double-struck-bold',
    name: 'Double-Struck Underline',
    description: 'Blackboard bold letters underlined — mathematical and distinctive.',
    category: 'decorative',
    tags: ['double struck', 'underline', 'math', 'combined'],
    map: DOUBLE_STRUCK_MAP,
    decorator: underline,
    example: transform('Hello World', DOUBLE_STRUCK_MAP, underline),
    platforms: ['discord', 'twitter', 'instagram'],
    relatedStyles: ['double-struck', 'underline-text', 'gothic-font', 'monospace-font', 'bold-text'],
    seoKeywords: ['double struck underline', 'blackboard bold underline', 'math font underline', 'outlined underline'],
    searchVolume: 3200,
  },
  {
    id: 'small-caps-bold',
    name: 'Small Caps Bold',
    description: 'Small capital letters in bold — authoritative and compact.',
    category: 'transform',
    tags: ['small caps', 'bold', 'compact', 'authoritative'],
    map: SMALL_CAPS_MAP,
    decorator: (text: string) => text.toUpperCase(),
    example: transform('Hello World', SMALL_CAPS_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook'],
    relatedStyles: ['small-caps', 'bold-text', 'superscript-text', 'fullwidth-text', 'monospace-font'],
    seoKeywords: ['small caps bold', 'bold small caps text', 'compact capital letters', 'authority font'],
    searchVolume: 3000,
  },
  {
    id: 'monospace-underline',
    name: 'Monospace Underline',
    description: 'Fixed-width typewriter letters with underline — like old terminal output.',
    category: 'decorative',
    tags: ['monospace', 'underline', 'terminal', 'typewriter', 'retro'],
    map: MONOSPACE_MAP,
    decorator: underline,
    example: transform('Hello World', MONOSPACE_MAP, underline),
    platforms: ['discord', 'twitter', 'instagram'],
    relatedStyles: ['monospace-font', 'underline-text', 'bold-text', 'sans-serif-font', 'double-struck'],
    seoKeywords: ['monospace underline font', 'typewriter underline text', 'terminal underline', 'code underline'],
    searchVolume: 2800,
  },
  {
    id: 'circled-bold',
    name: 'Circled Bold',
    description: 'Circled letters displayed in bold for extra impact.',
    category: 'geometric',
    tags: ['circled', 'bold', 'bubble', 'strong'],
    map: CIRCLED_MAP,
    decorator: (text: string) => text,
    example: transform('Hello World', CIRCLED_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'discord'],
    relatedStyles: ['circled-text', 'negative-circled', 'squared-text', 'bold-text', 'parenthesized-text'],
    seoKeywords: ['bold circled letters', 'strong circle text', 'circled bold font', 'bold bubble letters'],
    searchVolume: 2500,
  },
  {
    id: 'vaporwave-cursive',
    name: 'Vaporwave Cursive',
    description: 'Fullwidth cursive script letters spaced out — dreamy retro aesthetic.',
    category: 'width',
    tags: ['vaporwave', 'cursive', 'aesthetic', 'retro', 'dreamy'],
    map: CURSIVE_MAP,
    decorator: vaporwaveSpace,
    example: transform('Hello', CURSIVE_MAP, vaporwaveSpace),
    platforms: ['instagram', 'tiktok', 'twitter'],
    relatedStyles: ['vaporwave-text', 'cursive-font', 'fullwidth-text', 'aesthetic-text', 'bold-cursive-font'],
    seoKeywords: ['vaporwave cursive font', 'aesthetic cursive text', 'retro script generator', 'spaced cursive'],
    searchVolume: 2200,
  },
  {
    id: 'bold-hearts',
    name: 'Bold with Hearts',
    description: 'Bold mathematical text framed with heart symbols — strong yet romantic.',
    category: 'decorative',
    tags: ['bold', 'hearts', 'romantic', 'combined'],
    map: BOLD_MAP,
    decorator: hearts,
    example: transform('Hello World', BOLD_MAP, hearts),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook', 'whatsapp'],
    relatedStyles: ['bold-text', 'hearts-text', 'stars-text', 'cursive-font', 'sparkles-text'],
    seoKeywords: ['bold hearts text', 'bold love text generator', 'heart bold font', 'romantic bold text'],
    searchVolume: 2000,
  },
  {
    id: 'gothic-strikethrough',
    name: 'Gothic Strikethrough',
    description: 'Dark Fraktur letters crossed out — dramatic and rebellious.',
    category: 'script',
    tags: ['gothic', 'strikethrough', 'dark', 'rebellious'],
    map: GOTHIC_MAP,
    decorator: strikethrough,
    example: transform('Hello World', GOTHIC_MAP, strikethrough),
    platforms: ['discord', 'twitter', 'instagram', 'tiktok'],
    relatedStyles: ['gothic-font', 'strikethrough-text', 'bold-strikethrough', 'italic-strikethrough', 'zalgo-light'],
    seoKeywords: ['gothic strikethrough text', 'fraktur crossed out', 'dark strike text', 'gothic crossed font'],
    searchVolume: 1800,
  },
  {
    id: 'double-struck-strikethrough',
    name: 'Double-Struck Strikethrough',
    description: 'Blackboard bold letters with strikethrough — unique mathematical style.',
    category: 'decorative',
    tags: ['double struck', 'strikethrough', 'math', 'unique'],
    map: DOUBLE_STRUCK_MAP,
    decorator: strikethrough,
    example: transform('Hello World', DOUBLE_STRUCK_MAP, strikethrough),
    platforms: ['discord', 'twitter', 'instagram'],
    relatedStyles: ['double-struck', 'strikethrough-text', 'gothic-font', 'bold-strikethrough', 'monospace-font'],
    seoKeywords: ['double struck strikethrough', 'blackboard bold strike', 'math font strikethrough', 'outlined strike'],
    searchVolume: 1600,
  },
  {
    id: 'cursive-bold-strikethrough',
    name: 'Bold Cursive Strikethrough',
    description: 'Bold script letters with a strikethrough — stylish and dramatic.',
    category: 'script',
    tags: ['bold', 'cursive', 'strikethrough', 'dramatic'],
    map: BOLD_CURSIVE_MAP,
    decorator: strikethrough,
    example: transform('Hello World', BOLD_CURSIVE_MAP, strikethrough),
    platforms: ['instagram', 'tiktok', 'twitter'],
    relatedStyles: ['bold-cursive-font', 'strikethrough-text', 'bold-strikethrough', 'cursive-font', 'italic-strikethrough'],
    seoKeywords: ['bold cursive strikethrough', 'script crossed text', 'fancy strikethrough', 'cursive crossed'],
    searchVolume: 1500,
  },
  {
    id: 'upside-down-bold',
    name: 'Upside Down Bold',
    description: 'Bold letters flipped upside down — wild and chaotic.',
    category: 'transform',
    tags: ['upside down', 'bold', 'flipped', 'chaotic'],
    map: UPSIDE_DOWN_MAP,
    decorator: (text: string) => text.split('').reverse().join(''),
    example: transform('Hello World', UPSIDE_DOWN_MAP, (t) => t.split('').reverse().join('')),
    platforms: ['instagram', 'tiktok', 'twitter', 'discord'],
    relatedStyles: ['upside-down-text', 'mirrored-text', 'bold-text', 'zalgo-light', 'vaporwave-text'],
    seoKeywords: ['upside down bold text', 'flipped bold letters', 'inverted bold font', 'flip bold text'],
    searchVolume: 1400,
  },
  {
    id: 'fullwidth-bold',
    name: 'Fullwidth Bold',
    description: 'Wide fullwidth characters in bold weight — maximum width and impact.',
    category: 'width',
    tags: ['fullwidth', 'bold', 'wide', 'maximum', 'impact'],
    map: FULLWIDTH_MAP,
    example: transform('Hello World', FULLWIDTH_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook'],
    relatedStyles: ['fullwidth-text', 'vaporwave-text', 'bold-text', 'aesthetic-text', 'monospace-font'],
    seoKeywords: ['fullwidth bold text', 'wide bold letters', 'bold fullwidth font', 'thick wide text'],
    searchVolume: 1300,
  },
  {
    id: 'superscript-italic',
    name: 'Superscript Italic',
    description: 'Raised superscript characters — tiny elevated letters with italic style.',
    category: 'transform',
    tags: ['superscript', 'italic', 'raised', 'tiny', 'elevated'],
    map: SUPERSCRIPT_MAP,
    example: transform('Hello World', SUPERSCRIPT_MAP),
    platforms: ['instagram', 'tiktok', 'discord', 'twitter'],
    relatedStyles: ['superscript-text', 'subscript-text', 'small-caps', 'italic-font', 'bold-text'],
    seoKeywords: ['superscript italic text', 'raised italic letters', 'tiny italic superscript', 'elevated italic'],
    searchVolume: 1200,
  },
  {
    id: 'parenthesized-bold',
    name: 'Bold Parenthesized',
    description: 'Parenthesized letters presented in bold — enclosed and emphatic.',
    category: 'geometric',
    tags: ['parenthesized', 'bold', 'enclosed', 'emphatic'],
    map: PARENTHESIZED_MAP,
    example: transform('Hello World', PARENTHESIZED_MAP),
    platforms: ['instagram', 'tiktok', 'twitter', 'facebook'],
    relatedStyles: ['parenthesized-text', 'circled-text', 'squared-text', 'bold-text', 'negative-circled'],
    seoKeywords: ['bold parenthesized letters', 'strong bracket text', 'enclosed bold letters', 'bold in brackets'],
    searchVolume: 1100,
  },
  {
    id: 'monospace-bold',
    name: 'Monospace Bold',
    description: 'Fixed-width characters in bold — code aesthetic with heavy weight.',
    category: 'decorative',
    tags: ['monospace', 'bold', 'code', 'terminal', 'heavy'],
    map: MONOSPACE_MAP,
    decorator: (text: string) => text,
    example: transform('Hello World', MONOSPACE_MAP),
    platforms: ['discord', 'twitter', 'instagram', 'tiktok'],
    relatedStyles: ['monospace-font', 'bold-text', 'sans-bold', 'double-struck', 'gothic-font'],
    seoKeywords: ['monospace bold text', 'bold code font', 'heavy typewriter text', 'bold terminal font'],
    searchVolume: 1000,
  },
];

// ── Combination styles (programmatically generated) ───────────────────────────
const _existingIds = new Set(STYLES.map(s => s.id));
const _combos = generateCombinationStyles(_existingIds);
STYLES.push(..._combos);

// Convenience lookup by ID
export const STYLES_BY_ID: Record<string, StyleDefinition> = Object.fromEntries(
  STYLES.map(s => [s.id, s])
);

export function getStyleById(id: string): StyleDefinition | undefined {
  return STYLES_BY_ID[id];
}

export function getStylesByCategory(category: StyleCategory): StyleDefinition[] {
  return STYLES.filter(s => s.category === category);
}

export function getStylesByPlatform(platform: PlatformId): StyleDefinition[] {
  return STYLES.filter(s => s.platforms.includes(platform));
}

export function getRelatedStyles(id: string): StyleDefinition[] {
  const style = STYLES_BY_ID[id];
  if (!style) return [];
  return style.relatedStyles
    .map(rid => STYLES_BY_ID[rid])
    .filter(Boolean) as StyleDefinition[];
}

export function getTopStylesByVolume(n: number = 10): StyleDefinition[] {
  return [...STYLES].sort((a, b) => b.searchVolume - a.searchVolume).slice(0, n);
}
